version: "3.7"
services:
  db:
    build: mysql
    image: nareru_db
    container_name: nareru_db
    ports:
      - 3306:3306
  app:
    build: rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: nareru_app
    container_name: nareru_app
    ports:
      - 3000:3000
    volumes:
      - ./rails:/nareruApp
    depends_on:
      - db